- hosts: all
  become: no
  tasks:
    # Git and Nginx
    - name: Install git, nginx
      become: yes
      apt:
        name:
          - git
          - nginx
        update_cache: yes
    # Download repository
    - name: Download frontend from repository
      git:
        dest: angular
        repo: https://github.com/spring-petclinic/spring-petclinic-angular.git
        clone: yes
        force: yes
    # Configure repository
    - name: Configure REST address
      lineinfile:
        dest: ./angular/src/environments/environment.prod.ts
        regexp: '^\s*REST_API_URL:'
        line: "REST_API_URL: 'http://{{nginx_host}}:{{nginx_port}}/petclinic/api/'"
    # NodeJS and NPM
    - name: Update nodejs information
      become: yes
      shell:
        cmd: curl -sL https://deb.nodesource.com/setup_16.x | bash -
        warn: false
    - name: Install nodejs, npm
      become: yes
      apt:
        name: nodejs
        state: latest
    - name: Install npm packages
      npm:
        path: ./angular
    - name: Install npm angular
      become: yes
      npm:
        name: '@angular/cli'
        version: '11.2.11'
        global: yes
    # Build angular
    - name: Build frontend
      become: yes
      shell:
        cmd: ng build --prod --base-href=/petclinic/ --output-path=/var/www/html/petclinic/
        chdir: angular
    # Setup Nginx
    - name: Remove default nginx config
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Upload nginx angular config
      become: yes
      template:
        src: ./sent_config/nginx-angular.conf.j2
        dest: /etc/nginx/sites-enabled/nginx-angular.conf
    # Run
    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted