- hosts: ungrouped[0]
  tasks:

- name: MySQL
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_master }}'
- name: REST
  import_playbook: rest-playbook.yml
  vars:
    machine: '{{ rest_write }}'
- name: Angular
  import_playbook: angular-playbook.yml
  vars:
    machine: '{{ angular }}'
