- hosts: ungrouped[0]
  tasks:

- name: MySQL Master
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_master }}'
    mysql_port: '{{ mysql_master_port }}'
    mysql_instance_type: 'master'
- name: MySQL Slave
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_slave }}'
    mysql_port: '{{ mysql_slave_port }}'
    mysql_instance_type: 'slave'
- name: REST
  import_playbook: rest-playbook-2.yml
  vars:
    machine: '{{ rest_write }}'
    rest_host: '{{ rest_write_host }}'
    rest_port: '{{ rest_write_port }}'
- name: Angular
  import_playbook: angular-playbook.yml
  vars:
    machine: '{{ angular }}'
