- hosts: ungrouped[0]
  tasks:

- name: MySQL Master
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_master }}'
    mysql_instance_type: 'master'
- name: MySQL Slave
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_slave }}'
    mysql_instance_type: 'slave'
- name: REST Write
  import_playbook: rest-playbook-2.yml
  vars:
    machine: '{{ rest_write }}'
    rest_host: '{{ rest_write_host }}'
    rest_port: '{{ rest_write_port }}'
- name: REST Read
  import_playbook: rest-playbook-2.yml
  vars:
    machine: '{{ rest_read }}'
    rest_host: '{{ rest_read_host }}'
    rest_port: '{{ rest_read_port }}'
- name: Load Balancer
  import_playbook: nginx-playbook.yml
  vars:
    machine: '{{ load_balancer }}'
- name: Angular
  import_playbook: angular-playbook.yml
  vars:
    machine: '{{ angular }}'
