- hosts: ungrouped[0]
  tasks:

- name: MySQL
  import_playbook: mysql-playbook.yml
  vars:
    machine: '{{ mysql_master }}'
    mysql_port: '{{ mysql_master_port }}'
    mysql_instance_type: master
- name: REST
  import_playbook: rest-playbook.yml
  vars:
    machine: '{{ rest_write }}'
    mysql_host: '{{ mysql_master_host }}'
    mysql_port: '{{ mysql_master_port }}'
    rest_host: '{{ rest_write_host }}'
    rest_port: '{{ rest_write_port }}'
- name: Angular
  import_playbook: angular-playbook.yml
  vars:
    machine: '{{ angular }}'
