- hosts: all
  become: no
  tasks:
    - name: Install mysql
      become: yes
      apt:
        name: mysql-server
        state: latest
    - name: Configure mysql port
      become: yes
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#?\s*port\s*='
        line: 'port = {{ db_port }}'
    - name: Configure mysql bind address
      become: yes
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#?\s*bind-address\s*='
        line: 'bind-address = 0.0.0.0'
    - name: Restart mysql service
      become: yes
      service:
        name: mysql
        state: restarted
    - name: Download mysql init script
      get_url:
        url: https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/29287912f1976ec01fc364e99a5798d6d8a3d6c7/src/main/resources/db/mysql/initDB.sql
        dest: .
    - name: Change mysql init script user data privileges
      lineinfile:
        path: ./initDB.sql
        regexp: "^GRANT "
        line: "GRANT ALL PRIVILEGES ON petclinic.* TO '{{ db_user }}'@'%';"
    - name: Change mysql init script db name
      replace:
        path: ./initDB.sql
        regexp: 'petclinic'
        replace: '{{ db_name }}'
    - name: Add mysql init script privilege flushing
      lineinfile:
        path: ./initDB.sql
        insertbefore: "^GRANT "
        line: "FLUSH PRIVILEGES;"
    - name: Add mysql init script user creation command
      lineinfile:
        path: ./initDB.sql
        insertbefore: "^GRANT "
        line: "CREATE USER IF NOT EXISTS '{{ db_user }}' IDENTIFIED BY '{{ db_pass }}';"
    - name: Execute mysql init script
      become: yes
      shell: cat ./initDB.sql | mysql
    - name: Download mysql data script
      get_url:
        url: https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/29287912f1976ec01fc364e99a5798d6d8a3d6c7/src/main/resources/db/mysql/populateDB.sql
        dest: .
    - name: Execute mysql data script
      become: yes
      shell: 'cat ./populateDB.sql | mysql {{ db_name }}'
