- hosts: "{{ machine }}"
  become: no
  tasks:
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Remove default nginx config
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Upload nginx load balancer config
      become: yes
      template:
        src: ./sent_config/nginx-load-balancer.conf.j2
        dest: /etc/nginx/sites-enabled/nginx-load-balancer.conf
    - name: Reload nginx
      become: yes
      shell: 'nginx -s reload'
