- hosts: all
  become: no
  tasks:
    - name: Install git
      become: yes
      apt:
        name: git
        state: latest
    - name: Install JDK
      become: yes
      apt:
        name: openjdk-8-jdk
        state: latest
    - name: Install JRE
      become: yes
      apt:
        name: openjdk-8-jre
        state: latest
    - name: Clone repository
      git:
        repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
        dest: ./rest
    - name: Build REST
      command:
        cmd: './mvnw package -Dmaven.test.skip=true'
        chdir: ./rest
    - name: Check if port is free
      register: busy_port
      ignore_errors: true
      command:
        cmd: 'lsof -Pti :{{ rest_port }} -sTCP:LISTEN'
    - name: Kill process occupying needed port (what could possibly go wrong)
      when: busy_port is succeeded
      command:
        cmd: 'kill {{ busy_port.stdout }}'
    - name: Run REST
      shell: "nohup java -jar ./rest/target/spring-petclinic-rest-2.4.2.jar --server.port={{ rest_port }} --spring.profiles.active=mysql,spring-data-jpa --spring.datasource.url=jdbc:mysql://{{ db_user }}:{{ db_pass }}@{{ db_host | default('localhost') }}:{{ db_port }}/{{ db_name }}?useUnicode=true &"
