all:
    vars:
        mysql_master_host: "{{ hostvars[mysql_master]['ansible_host'] }}"
        mysql_master_port: 30603 #
        mysql_slave_host: "{{ hostvars[mysql_slave]['ansible_host'] }}"
        mysql_slave_port: 30604 #
        mysql_user: pc
        mysql_pass: pc
        mysql_name: petclinic
        mysql_root_pass: balbinka

        rest_read_host: "{{ hostvars[rest_read]['ansible_host'] }}"
        rest_read_port: 7777 #
        rest_write_host: "{{ hostvars[rest_write]['ansible_host'] }}"
        rest_write_port: 7776 #

        load_balancer_host: "{{ hostvars[load_balancer | default(rest_write)]['ansible_host'] }}"
        load_balancer_port: "{{ rest_write_port }}"
        angular_port: 8080 #
